apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-demo-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://dhenne.github.io/helm-charts/
    chart: spring-boot-helm-demo
    targetRevision: 0.1.6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
