apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 10.15.0
    helm:
      values: |
        service:
          type: NodePort
        providers:
          kubernetesIngress:
            ingressEndpoint:
              # only works for service type loadbalancer dynamically
              # see also: https://github.com/traefik/traefik/issues/7972
              ip: 192.168.49.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
